version: '3'
 
services:
  dbmatomo:
    image: mariadb:10.5.3
    volumes:
      - dbmatomo:/var/lib/mysql
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=matomo
 
  matomo:
    image: matomo
    volumes:
      - matomo:/var/www/html
    environment:
      - MATOMO_DATABASE_HOST=dbmatomo
      - VIRTUAL_HOST=
      - MYSQL_DATABASE=matomo
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MATOMO_DATABASE_ADAPTER=mysql
      - MATOMO_DATABASE_TABLES_PREFIX=matomo_
      - MATOMO_DATABASE_USERNAME=root
      - MATOMO_DATABASE_PASSWORD=root
      - MATOMO_DATABASE_DBNAME=matomo
    ports:
      - 8080:80
 
volumes:
  - dbmatomo:
  - matomo:
